'use strict';
const groups = require('./optionGroups');

const img = (id, alt) => [{ url: 'https://images.unsplash.com/photo-' + id + '?auto=format&fit=crop&w=900&q=80', alt }];

module.exports = [
  /* ------------------------------ Salad Bowls ------------------------------ */
  {
    name: 'Sprouts & Veggie Salad',
    category: 'Salad Bowls',
    price: 120,
    foodType: 'veg',
    shortDescription: 'Crunchy mixed sprouts tossed with fresh cucumber, tomato, carrot and a lemon-pepper finish.',
    description:
      'Our everyday favourite. Moong and moth sprouts are steamed just enough to stay crisp, then tossed with hand-chopped cucumber, tomato, carrot and onion. Finished with lemon juice, rock salt and cracked black pepper - no cream, no mayo, no deep frying.',
    images: img('1512621776951-a57141f2eefd', 'Sprouts and vegetable salad bowl'),
    nutrition: { calories: 210, protein: 12, carbs: 28, fat: 4, fibre: 8, sugar: 6, sodium: 320, iron: 3.2, calcium: 65, potassium: 480, vitaminA: 210 },
    servingSize: '300 g bowl',
    prepTimeMinutes: 10,
    ingredients: ['Moong sprouts', 'Moth sprouts', 'Cucumber', 'Tomato', 'Carrot', 'Onion', 'Lemon', 'Rock salt', 'Black pepper'],
    allergens: [],
    badges: ['HIGH PROTEIN', 'HIGH FIBRE', 'LESS OIL', 'UNDER 300 KCAL'],
    dietTags: ['high-protein', 'high-fibre', 'less-oil', 'under-300-kcal', 'vegan'],
    optionGroups: groups.salad,
    isPopular: true,
    isFeatured: true,
    order: 1,
  },
  {
    name: 'Paneer Quinoa Salad',
    category: 'Salad Bowls',
    price: 160,
    foodType: 'veg',
    shortDescription: 'Fluffy quinoa, grilled paneer cubes and rainbow veggies with a roasted sesame dressing.',
    description:
      'A properly filling bowl. Quinoa is cooked till fluffy and cooled, then layered with lightly grilled paneer, bell peppers, cherry tomatoes and greens. The roasted sesame dressing is made in-house with a spoon of oil, nothing more.',
    images: img('1467003909585-2f8a72700288', 'Paneer and quinoa salad bowl'),
    nutrition: { calories: 340, protein: 21, carbs: 32, fat: 13, fibre: 7, sugar: 5, sodium: 380, iron: 3.8, calcium: 260, potassium: 520, vitaminA: 340 },
    servingSize: '320 g bowl',
    prepTimeMinutes: 15,
    ingredients: ['Quinoa', 'Paneer', 'Bell peppers', 'Cherry tomato', 'Lettuce', 'Sesame seeds', 'Olive oil', 'Herbs'],
    allergens: ['Milk', 'Sesame'],
    badges: ['HIGH PROTEIN', 'HIGH FIBRE', 'QUINOA BASED', 'LESS OIL'],
    dietTags: ['high-protein', 'high-fibre', 'quinoa-based', 'less-oil'],
    optionGroups: groups.salad,
    isPopular: true,
    isFeatured: true,
    order: 2,
  },

  /* --------------------------------- Wraps --------------------------------- */
  {
    name: 'Paneer Tikka Wrap',
    category: 'Wraps',
    price: 140,
    foodType: 'veg',
    shortDescription: 'Marinated grilled paneer, onions and mint chutney rolled in a soft whole wheat roti.',
    description:
      'Paneer is marinated in hung curd and tikka spices, grilled on a hot tawa and rolled into a fresh whole wheat roti with onion, tomato, lettuce and mint chutney. Nothing is fried and no cheese slice is hiding inside.',
    images: img('1600335895229-6e75511892c8', 'Paneer tikka wrap'),
    nutrition: { calories: 380, protein: 19, carbs: 42, fat: 14, fibre: 6, sugar: 4, sodium: 520, iron: 2.9, calcium: 290, potassium: 380, vitaminA: 180 },
    servingSize: '1 wrap (230 g)',
    prepTimeMinutes: 15,
    ingredients: ['Whole wheat roti', 'Paneer', 'Hung curd', 'Onion', 'Tomato', 'Lettuce', 'Mint chutney', 'Tikka masala'],
    allergens: ['Milk', 'Gluten'],
    badges: ['HIGH PROTEIN', 'WHOLE GRAIN', 'LESS OIL'],
    dietTags: ['high-protein', 'whole-grain', 'less-oil'],
    optionGroups: groups.wrap,
    isPopular: true,
    isFeatured: true,
    order: 3,
  },
  {
    name: 'Chicken Tikka Wrap',
    category: 'Wraps',
    price: 160,
    foodType: 'non-veg',
    shortDescription: 'Char-grilled chicken tikka with crunchy salad and mint chutney in a whole wheat roti.',
    description:
      'Boneless chicken thigh is marinated overnight in curd, ginger, garlic and tikka spices, then char-grilled to order. Rolled with onion, lettuce and mint chutney in a whole wheat roti. High protein, genuinely filling.',
    images: img('1626700051175-6818013e1d4f', 'Chicken tikka wrap'),
    nutrition: { calories: 410, protein: 28, carbs: 40, fat: 13, fibre: 5, sugar: 4, sodium: 580, iron: 3.1, calcium: 120, potassium: 460, vitaminA: 150 },
    servingSize: '1 wrap (240 g)',
    prepTimeMinutes: 18,
    ingredients: ['Whole wheat roti', 'Chicken', 'Curd', 'Ginger', 'Garlic', 'Onion', 'Lettuce', 'Mint chutney'],
    allergens: ['Milk', 'Gluten'],
    badges: ['HIGH PROTEIN', 'WHOLE GRAIN', 'LESS OIL'],
    dietTags: ['high-protein', 'whole-grain', 'less-oil'],
    optionGroups: groups.wrap,
    isPopular: true,
    order: 4,
  },
  {
    name: 'Brown Chana Hummus Wrap',
    category: 'Wraps',
    price: 130,
    foodType: 'veg',
    shortDescription: 'Spiced brown chana and creamy hummus with crisp veggies in a multigrain roti.',
    description:
      'A fully plant-based wrap. Brown chana is simmered with cumin and amchur, then rolled with house-made hummus, cucumber, onion and lettuce in a multigrain roti. Excellent fibre, no dairy.',
    images: img('1529006557810-274b9b2fc783', 'Brown chana hummus wrap'),
    nutrition: { calories: 350, protein: 15, carbs: 48, fat: 10, fibre: 11, sugar: 5, sodium: 460, iron: 4.2, calcium: 110, potassium: 540, vitaminA: 120 },
    servingSize: '1 wrap (235 g)',
    prepTimeMinutes: 14,
    ingredients: ['Multigrain roti', 'Brown chana', 'Hummus', 'Cucumber', 'Onion', 'Lettuce', 'Cumin', 'Amchur'],
    allergens: ['Gluten', 'Sesame'],
    badges: ['HIGH PROTEIN', 'HIGH FIBRE', 'WHOLE GRAIN', 'LESS OIL'],
    dietTags: ['high-protein', 'high-fibre', 'whole-grain', 'less-oil', 'vegan'],
    optionGroups: groups.wrap,
    order: 5,
  },

  /* ------------------------------- Sandwiches ------------------------------ */
  {
    name: 'Grilled Paneer Sandwich',
    category: 'Sandwiches',
    price: 130,
    foodType: 'veg',
    shortDescription: 'Grilled paneer, capsicum and onion pressed between multigrain bread with mint chutney.',
    description:
      'Multigrain bread, a thick layer of masala paneer, capsicum and onion, toasted in a press with the barest brush of butter. Cut into triangles and served with mint chutney.',
    images: img('1528735602780-2552fd46c7af', 'Grilled paneer sandwich'),
    nutrition: { calories: 320, protein: 17, carbs: 36, fat: 12, fibre: 6, sugar: 4, sodium: 480, iron: 2.6, calcium: 280, potassium: 320, vitaminA: 160 },
    servingSize: '2 halves (200 g)',
    prepTimeMinutes: 12,
    ingredients: ['Multigrain bread', 'Paneer', 'Capsicum', 'Onion', 'Mint chutney', 'Butter (minimal)', 'Chaat masala'],
    allergens: ['Milk', 'Gluten'],
    badges: ['HIGH PROTEIN', 'WHOLE GRAIN', 'LESS OIL'],
    dietTags: ['high-protein', 'whole-grain', 'less-oil'],
    optionGroups: groups.sandwich,
    isPopular: true,
    order: 6,
  },
  {
    name: 'Veggie Sandwich',
    category: 'Sandwiches',
    price: 110,
    foodType: 'veg',
    shortDescription: 'Cucumber, tomato, beetroot and carrot layered with mint chutney on multigrain bread.',
    description:
      'The classic Bombay-style veg sandwich, made lighter. Thin-sliced cucumber, tomato, beetroot, carrot and boiled potato with mint chutney and chaat masala on multigrain bread. Light, refreshing and easy on the pocket.',
    images: img('1553909489-cd47e0907980', 'Fresh veggie sandwich'),
    nutrition: { calories: 240, protein: 8, carbs: 40, fat: 5, fibre: 7, sugar: 6, sodium: 420, iron: 2.1, calcium: 90, potassium: 420, vitaminA: 380 },
    servingSize: '2 halves (190 g)',
    prepTimeMinutes: 10,
    ingredients: ['Multigrain bread', 'Cucumber', 'Tomato', 'Beetroot', 'Carrot', 'Potato', 'Mint chutney', 'Chaat masala'],
    allergens: ['Gluten'],
    badges: ['HIGH FIBRE', 'WHOLE GRAIN', 'LESS OIL', 'UNDER 300 KCAL'],
    dietTags: ['high-fibre', 'whole-grain', 'less-oil', 'under-300-kcal', 'vegan'],
    optionGroups: groups.sandwich,
    order: 7,
  },

  /* --------------------------------- Cutlets -------------------------------- */
  {
    name: 'Oats & Vegetable Cutlet',
    category: 'Cutlets',
    price: 110,
    foodType: 'veg',
    shortDescription: 'Rolled oats bound with carrot, beans and peas, pan-seared golden with very little oil.',
    description:
      'Rolled oats replace breadcrumbs entirely here, bound with grated carrot, French beans, peas and warm spices. Shallow-cooked on a tawa - never deep fried - and served with fresh mint chutney.',
    images: img('1601050690597-df0568f70950', 'Oats and vegetable cutlets'),
    nutrition: { calories: 260, protein: 9, carbs: 38, fat: 8, fibre: 7, sugar: 3, sodium: 400, iron: 2.4, calcium: 80, potassium: 360, vitaminA: 420 },
    servingSize: '2 pieces (160 g)',
    prepTimeMinutes: 15,
    ingredients: ['Rolled oats', 'Carrot', 'French beans', 'Green peas', 'Potato', 'Ginger', 'Green chilli', 'Coriander'],
    allergens: ['Gluten'],
    badges: ['HIGH FIBRE', 'MILLET/OATS BASED', 'LESS OIL', 'UNDER 300 KCAL'],
    dietTags: ['high-fibre', 'oats-based', 'less-oil', 'under-300-kcal', 'vegan'],
    optionGroups: groups.cutlet,
    isPopular: true,
    order: 8,
  },
  {
    name: 'Potato Veggie Cutlet',
    category: 'Cutlets',
    price: 100,
    foodType: 'veg',
    shortDescription: 'Our most affordable snack - spiced potato and mixed veg patties, pan-seared crisp.',
    description:
      'Comfort food done sensibly. Boiled potato mashed with peas, carrot, coriander and green chilli, shaped into patties and pan-seared until crisp on the outside. Starts our menu at Rs. 100.',
    images: img('1619740455993-9e612b1af08a', 'Potato vegetable cutlets'),
    nutrition: { calories: 240, protein: 6, carbs: 40, fat: 7, fibre: 5, sugar: 3, sodium: 420, iron: 1.9, calcium: 60, potassium: 480, vitaminA: 300 },
    servingSize: '2 pieces (155 g)',
    prepTimeMinutes: 13,
    ingredients: ['Potato', 'Green peas', 'Carrot', 'Coriander', 'Green chilli', 'Ginger', 'Garam masala'],
    allergens: [],
    badges: ['LESS OIL', 'UNDER 300 KCAL'],
    dietTags: ['less-oil', 'under-300-kcal', 'vegan'],
    optionGroups: groups.cutlet,
    order: 9,
  },
  {
    name: 'Chicken Cutlets',
    category: 'Cutlets',
    price: 150,
    foodType: 'non-veg',
    shortDescription: 'Minced chicken patties bound with oats and herbs, pan-seared for a high-protein bite.',
    description:
      'Lean chicken mince mixed with rolled oats, onion, coriander and pepper, then pan-seared on both sides. No breadcrumb coating, no deep frying - just a clean, high-protein snack with yogurt dip.',
    images: img('1604908176997-125f25cc6f3d', 'Chicken cutlets'),
    nutrition: { calories: 300, protein: 26, carbs: 18, fat: 13, fibre: 3, sugar: 2, sodium: 520, iron: 2.2, calcium: 60, potassium: 400, vitaminA: 90 },
    servingSize: '2 pieces (170 g)',
    prepTimeMinutes: 18,
    ingredients: ['Chicken mince', 'Rolled oats', 'Onion', 'Coriander', 'Black pepper', 'Ginger', 'Garlic'],
    allergens: ['Gluten'],
    badges: ['HIGH PROTEIN', 'MILLET/OATS BASED', 'LESS OIL'],
    dietTags: ['high-protein', 'oats-based', 'less-oil'],
    optionGroups: groups.cutlet,
    order: 10,
  },

  /* -------------------------------- Smoothies ------------------------------- */
  {
    name: 'Banana-Oats Smoothie',
    category: 'Smoothies',
    price: 120,
    foodType: 'veg',
    shortDescription: 'Ripe banana blended with rolled oats and toned milk - a genuinely filling drink.',
    description:
      'Two ripe bananas, a handful of rolled oats, toned milk and a pinch of cinnamon. Naturally sweet with zero added sugar or syrup. Thick enough to count as a snack on its own.',
    images: img('1505252585461-04db1eb84625', 'Banana oats smoothie'),
    nutrition: { calories: 290, protein: 11, carbs: 48, fat: 6, fibre: 6, sugar: 22, sodium: 110, iron: 1.8, calcium: 240, potassium: 720, vitaminA: 120 },
    servingSize: '350 ml',
    prepTimeMinutes: 8,
    ingredients: ['Banana', 'Rolled oats', 'Toned milk', 'Cinnamon'],
    allergens: ['Milk', 'Gluten'],
    badges: ['HIGH FIBRE', 'MILLET/OATS BASED', 'NO ADDED SUGAR', 'UNDER 300 KCAL'],
    dietTags: ['high-fibre', 'oats-based', 'fruit-based', 'under-300-kcal'],
    optionGroups: groups.smoothie,
    isPopular: true,
    isFeatured: true,
    order: 11,
  },
  {
    name: 'Berry-Yogurt Smoothie',
    category: 'Smoothies',
    price: 150,
    foodType: 'veg',
    shortDescription: 'Mixed berries whipped with thick yogurt - tangy, creamy and protein-rich.',
    description:
      'Strawberries, blueberries and black grapes blended with thick set yogurt and a touch of honey. Rich colour, real fruit, no artificial flavouring and no colour powder.',
    images: img('1553530666-ba11a7da3888', 'Berry yogurt smoothie'),
    nutrition: { calories: 260, protein: 14, carbs: 36, fat: 6, fibre: 5, sugar: 24, sodium: 95, iron: 1.2, calcium: 320, potassium: 480, vitaminA: 140 },
    servingSize: '350 ml',
    prepTimeMinutes: 8,
    ingredients: ['Strawberry', 'Blueberry', 'Black grapes', 'Set yogurt', 'Honey'],
    allergens: ['Milk'],
    badges: ['HIGH PROTEIN', 'FRUIT BASED', 'UNDER 300 KCAL'],
    dietTags: ['high-protein', 'fruit-based', 'under-300-kcal'],
    optionGroups: groups.smoothie,
    isPopular: true,
    order: 12,
  },
  {
    name: 'Mango-Chia Smoothie',
    category: 'Smoothies',
    price: 130,
    foodType: 'veg',
    shortDescription: 'Alphonso mango blended with curd and soaked chia seeds for extra fibre.',
    description:
      'Seasonal mango pulp blended with fresh curd, finished with soaked chia seeds that give it body and a fibre boost. Served chilled, no ice cream, no sugar syrup.',
    images: img('1623065422902-30a2d299bbe4', 'Mango chia smoothie'),
    nutrition: { calories: 270, protein: 9, carbs: 44, fat: 7, fibre: 8, sugar: 26, sodium: 90, iron: 1.6, calcium: 220, potassium: 460, vitaminA: 620 },
    servingSize: '350 ml',
    prepTimeMinutes: 8,
    ingredients: ['Mango', 'Curd', 'Chia seeds', 'Cardamom'],
    allergens: ['Milk'],
    badges: ['HIGH FIBRE', 'FRUIT BASED', 'UNDER 300 KCAL'],
    dietTags: ['high-fibre', 'fruit-based', 'under-300-kcal'],
    optionGroups: groups.smoothie,
    order: 13,
  },

  /* -------------------------------- Oats Jars ------------------------------- */
  {
    name: 'Yogurt Oats with Fruits',
    category: 'Oats Jars',
    price: 140,
    foodType: 'veg',
    shortDescription: 'Overnight oats layered with thick yogurt, banana, apple and pomegranate.',
    description:
      'Rolled oats soaked overnight in milk, layered with thick yogurt and topped with banana, apple and pomegranate. Comes sealed in a spill-proof jar with a spoon - ideal for a desk drawer or a hostel fridge.',
    images: img('1517093157656-b9eccef91cb1', 'Yogurt oats jar with fruits'),
    nutrition: { calories: 320, protein: 15, carbs: 50, fat: 7, fibre: 9, sugar: 20, sodium: 120, iron: 2.4, calcium: 300, potassium: 560, vitaminA: 160 },
    servingSize: '300 ml jar',
    prepTimeMinutes: 10,
    ingredients: ['Rolled oats', 'Milk', 'Set yogurt', 'Banana', 'Apple', 'Pomegranate', 'Honey'],
    allergens: ['Milk', 'Gluten'],
    badges: ['HIGH PROTEIN', 'HIGH FIBRE', 'MILLET/OATS BASED', 'WHOLE GRAIN'],
    dietTags: ['high-protein', 'high-fibre', 'oats-based', 'fruit-based', 'whole-grain'],
    optionGroups: groups.oatsJar,
    isPopular: true,
    isFeatured: true,
    order: 14,
  },
  {
    name: 'Chocolate-Banana Oats',
    category: 'Oats Jars',
    price: 130,
    foodType: 'veg',
    shortDescription: 'Cocoa-laced overnight oats with banana slices and roasted almonds.',
    description:
      'Unsweetened cocoa stirred through overnight oats with mashed banana for natural sweetness, topped with sliced banana and roasted almond slivers. Tastes like dessert, behaves like breakfast.',
    images: img('1484723091739-30a097e8f929', 'Chocolate banana oats jar'),
    nutrition: { calories: 330, protein: 12, carbs: 52, fat: 9, fibre: 9, sugar: 18, sodium: 110, iron: 3.1, calcium: 210, potassium: 640, vitaminA: 90 },
    servingSize: '300 ml jar',
    prepTimeMinutes: 10,
    ingredients: ['Rolled oats', 'Milk', 'Cocoa powder', 'Banana', 'Almonds', 'Honey'],
    allergens: ['Milk', 'Gluten', 'Nuts'],
    badges: ['HIGH FIBRE', 'MILLET/OATS BASED', 'WHOLE GRAIN', 'NO ADDED SUGAR'],
    dietTags: ['high-fibre', 'oats-based', 'fruit-based', 'whole-grain'],
    optionGroups: groups.oatsJar,
    order: 15,
  },
];
